version: "1.0"
services:
  graphiti-api:
    type: service
    name: graphiti-api
    source:
      type: git
      repo: https://github.com/YOUR_USERNAME/graphiti
      branch: main
      project_root: .
    dockerfile: Dockerfile
    port: 8000
    env:
      GRAPHITI_API_PORT: "8000"
      NEO4J_URI: "bolt://graphiti-neo4j:7687"
      NEO4J_USERNAME: "neo4j"
      NEO4J_PASSWORD: "your_strong_password"
    domains:
      - name: api.graphiti.example.com
        enable_https: true

  graphiti-ui:
    type: static
    name: graphiti-ui
    source:
      type: git
      repo: https://github.com/YOUR_USERNAME/graphiti
      branch: main
      project_root: ui
    build:
      install: npm install
      command: npm run build
      output: build
    env:
      VITE_GRAPHITI_API_URL: "https://api.graphiti.example.com"
    domains:
      - name: graphiti.example.com
        enable_https: true

  graphiti-neo4j:
    type: database
    name: graphiti-neo4j
    image: neo4j:5
    port: 7687
    env:
      NEO4J_AUTH: "neo4j/your_strong_password"
    volumes:
      - /data
    domains: []
